const verificationTemplate = ({ title, name, topLogoURL, bottomLogoURL, verificationLink, unsubscribeLink }) => {
	return `<!doctypehtml><html xmlns=http://www.w3.org/1999/xhtml xmlns:o=urn:schemas-microsoft-com:office:office xmlns:v=urn:schemas-microsoft-com:vml><head><!--[if gte mso 9]><xml><o:officedocumentsettings><o:allowpng><o:pixelsperinch>96</o:pixelsperinch></o:officedocumentsettings></xml><![endif]--><meta content="text/html; charset=UTF-8"http-equiv=Content-Type><meta content="width=device-width,initial-scale=1"name=viewport><meta name=x-apple-disable-message-reformatting><!--[if !mso]><!--><meta content="IE=edge"http-equiv=X-UA-Compatible><!--<![endif]--><title>${title}</title><link href=https://fonts.googleapis.com rel=preconnect><link href=https://fonts.gstatic.com rel=preconnect crossorigin><link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro&display=swap"rel=stylesheet><style>*{font-family:"Be Vietnam Pro",sans-serif}a,a:hover,a:link,a:visited,a[href]{text-decoration:none!important;color:#00e}.link{text-decoration:underline!important}p,p:visited{font-size:15px;line-height:24px;font-weight:300;text-decoration:none;color:#000}h1{font-size:22px;line-height:24px;font-weight:400;text-decoration:none;color:#000}.ExternalClass font,.ExternalClass p,.ExternalClass span,.ExternalClass td{line-height:100%}.ExternalClass{width:100%}</style><body align=center style=text-align:center;margin:0;padding-top:10px;padding-bottom:10px;padding-left:0;padding-right:0;-webkit-text-size-adjust:100%;background-color:#f2f4f6;color:#000><div style=text-align:center><table align=center style=text-align:center;vertical-align:top;width:600px;max-width:600px;background-color:#fff width=600><tr><td style=width:596px;vertical-align:top;padding-left:0;padding-right:0;padding-top:15px;padding-bottom:15px width=596><img align=center alt=Logo height=85 src=${topLogoURL} style=width:180px;max-width:180px;height:85px;max-height:85px;text-align:center;color:#fff width=180></table><table align=center style=text-align:center;vertical-align:top;width:600px;max-width:600px;background-color:#fff width=600><tr><td style=width:596px;vertical-align:top;padding-left:30px;padding-right:30px;padding-top:10px;padding-bottom:40px width=596><h1 style=font-size:20px;line-height:24px;font-weight:600;text-decoration:none;color:#000>Click to verify your email</h1><p style=font-size:15px;line-height:24px;font-weight:400;text-decoration:none;color:#919293;text-align:left>Hi ${name},<br>To activate your Lifefind Account, please verify your email address. Your account will not be created until your email address is confirmed.</p><a href=${verificationLink} style="background-color:#f79858;font-size:15px;line-height:22px;font-weight:400;text-decoration:none;padding:12px 15px;color:#fff;border-radius:5px;display:inline-block;mso-padding-alt:0;min-width:60px"target=_blank><!--[if mso
    ]>
                  <i style="letter-spacing: 25px; mso-font-width: -100%; mso-text-raise: 30pt;">&nbsp;</i>
                <![endif
    ]--> <span style=mso-text-raise:15pt;color:#fff>Verify</span><!--[if mso
    ]>
                  <i style="letter-spacing: 25px; mso-font-width: -100%;">&nbsp;</i>
                <![endif
    ]--></a><p style=font-size:15px;line-height:24px;font-weight:400;text-decoration:none;color:#919293;text-align:left>If this request is not submitted by you, don't worry, Whoever submitted it cannot access your account without this code. To ensure the security of your account, it's recommended to change the password for your account.<p style=font-size:15px;line-height:24px;font-weight:400;text-decoration:none;color:#919293;text-align:left>Or, copy and paste the following URL into your browser:<br>${verificationLink}</table><table align=center style=text-align:center;vertical-align:top;width:600px;max-width:600px;background-color:#f79858 width=600><tr><td style=width:596px;vertical-align:top;padding-left:30px;padding-right:30px;padding-top:30px;padding-bottom:30px width=596><img align=center alt=Logo height=85 src=${bottomLogoURL} style=width:180px;max-width:180px;height:85px;max-height:85px;text-align:center;color:#fff width=180><p style=margin-bottom:0;font-size:13px;line-height:24px;font-weight:400;text-decoration:none;color:#fff><a href=https://livespring.tech style=text-decoration:underline;color:#fff target=_blank>livespring.tech</a><p style=margin-bottom:0;font-size:13px;line-height:24px;font-family:Helvetica,Arial,sans-serif;font-weight:400;text-decoration:none;color:#fff><a href=${unsubscribeLink} style=text-decoration:underline;color:#fff><u>Unsubscribe</u></a></table></div>`;
};

const verificationTemplateTextFallback = ({ verificationLink }) => {
	return `Click or paste this url in your browser to authenticate your account.
    ${verificationLink}
    If this request is not submitted by you, don't worry, Whoever submitted it cannot access your account without this code. To ensure the security of your account, it's recommended to change the password for your account.`;
};

export { verificationTemplate, verificationTemplateTextFallback };
